repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff-check
        types_or: [python, pyi]

      - id: ruff
        # Run the sort imports
        name: sort imports with ruff
        types_or: [python, pyi]
        args: [--select, I, --fix]

      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
